### PR TITLE
feat: add colors to topic pill

### PR DESCRIPTION
**Pull request by ArkaPrabhaChowdhury**
image

Current look.
@codewithvoid PTAL.

### CODE REVIEW

**Comment by codewithvoid** [comment]
@ArkaPrabhaChowdhury thanks for the PR. Small comments
1. How about keeping different pill color for different categories. E.g red for programming, teal for software-development etc. Color values can be added in [categories file](https://github.com/codewithvoid/AskDevs/blob/main/public/categories.json)
2. Should we reduce the size of pills to make them look more smooth. [Example](https://tailwindcomponents.com/component/buttons-pills)

image

**Comment by ArkaPrabhaChowdhury** [comment]
> @ArkaPrabhaChowdhury thanks for the PR. Small comments
> 
> 1. How about keeping different pill color for different categories. E.g red for programming, teal for software-development etc. Color values can be added in [categories file](https://github.com/codewithvoid/AskDevs/blob/main/public/categories.json)
> 2. Should we reduce the size of pills to make them look more smooth. [Example](https://tailwindcomponents.com/component/buttons-pills)
> 
> image

I have kept a different pill colour for different categories already. PTAL. Should I just add the corresponding colours to the categories.json file? 

I will try to make the pills look a bit smoother.

**Comment by ArkaPrabhaChowdhury** [comment]
image
I reduced the font size and added a bit of padding horizontally. Looks smoother imo.

**Comment by ArkaPrabhaChowdhury** [comment]
@codewithvoid PTAL.

**Comment by codewithvoid** [comment]
@ArkaPrabhaChowdhury Looks good for now. Will make amendments if needed.

**Pull request merged**
