### PR TITLE
Added topics in the Profile Card | Solves issue #170

### PR DESCRIPTION
**Pull request by ArkaPrabhaChowdhury**
image

This is how it looks now. 

Other than adding the topic name, I have also added a titleCase, which capitalizes the first letter of every topic name.

### CODE REVIEW

**Comment by ArkaPrabhaChowdhury** [comment]
Solves issue: https://github.com/codewithvoid/AskDevs/issues/170

**Comment by codewithvoid** [comment]
hey @ArkaPrabhaChowdhury change is looking good. Can you put a background to color to tags like pills [here](https://tailwind-elements.com/docs/standard/components/badges/)

**Comment by ArkaPrabhaChowdhury** [comment]
> hey @ArkaPrabhaChowdhury change is looking good. Can you put a background to color to tags like pills [here](https://tailwind-elements.com/docs/standard/components/badges/)

Sure! That sounds great. I will work on it asap.

**Comment by ArkaPrabhaChowdhury** [comment]
Hey @codewithvoid ! Please do check it now. Looks pretty clean.

**Comment by codewithvoid** [comment]
@ArkaPrabhaChowdhury looks good. 2 nit feedback
1. Use 1 pill item per topic. E.g separate pill for C++, Java in programming topics
2. Color code the pills. Different color for different category (can send this in separate PR)

**Comment by ArkaPrabhaChowdhury** [comment]
Hey @codewithvoid . 
image
Does this look good for separate pills?

**Comment by codewithvoid** [comment]
@ArkaPrabhaChowdhury yes. Can you make it smaller so that it comes in one line? Want to keep the card size fixed for all cards.

**Comment by ArkaPrabhaChowdhury** [comment]
Hey @codewithvoid PTAL

**Comment by codewithvoid** [comment]
Can't see the changes in preview. Let's merge and check. Will fix in follow up change if needed.

**Pull request merged**
