### PR TITLE
Fixed all issues reported

### PR DESCRIPTION
**Pull request by ibukunoluwanap**
### Issues fixed

- Created project logos
- Made navbar sticky and minimal
- Added home button for reload purpose on the logo at the navbar
- Created a full page background color gradient
- Redesign the UI

### CODE REVIEW

**Comment by ibukunoluwanap** [comment]
if you have time check this out @codewithvoid

**Comment by codewithvoid** [comment]
Thanks for the PR @ibukunoluwanap. Do you mind splitting the changes? Few changes like UI and logo design needs more discussion.

**Comment by ibukunoluwanap** [comment]
@codewithvoid Ok, should i fix the conflicts and send a merge again?

**Comment by codewithvoid** [comment]
Yes please. And preferably discuss planned changes on issue.

**Comment by ibukunoluwanap** [comment]
conflicts fixed.

**Review by ibukunoluwanap — COMMENTED** [review]
resolved conflicts but kept the gradient

**Comment by codewithvoid** [comment]
I see there are some merge conflicts. Can you create separate PR for gradient fix?

**Pull request closed without merging**
